Now able to open the Kinect device
Found two crashes:

1) asking for the device serial number would cause the app to crash
with EXC_BAD_ACCESS i386 GFLT

2) calling freenect2.openDevice(id, pipeline) would fail to build with
2 errors:

 2.1) ”libfreenect2::Freenect2::openDevice(std::string const&,
libfreenect2::PacketPipeline const*)", referenced from:
_ta_jit_kinect2_open in ta.jit.kinect2.o
ld: symbol(s) not found for architecture x86_64

2.2) clang: error: linker command failed with exit code 1 (use -v to
see invocation)

SOLUTION:
call freenect2.openDefaultDevice() which requires no arguments